#!/bin/bash

# This script generates docker-compose.prod.yml
# so you can use `docker compose -f docker-compose.prod.yml up` to start the production code
#
# it will remove lines containing  #!dev
# and restore commented lines containing #!prod


ROOT_DIR="$(dirname $0)/.."

cd $ROOT_DIR

>docker-compose.prod.yml cat <<EOF
# --------------------
# This file is auto-generated by ./scripts/prod-up.sh
#
# Do not directly edit!
# --------------------
$(sed -e '/#!dev/d' -e '/#!prod/s/# *//' docker-compose.yml)
EOF
